// Mock data for top sellers carousel

// Top Products
export const topProducts = [
    {
      _id: "bF-klhVOReGW",
      totalSales: 1287,
      title: "Cloud Computing Masterclass",
      thumbnail: "https://images.unsplash.com/photo-1603695762547-fba8d775c3a4?q=80&w=2940&auto=format&fit=crop",
      description: "Learn cloud computing in practical way and get a job",
      price: 2996,
      isFree: false,
      level: "Intermediate",
      tutorName: "Akash Singh",
      tutorImage: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=2787&auto=format&fit=crop",
      category: "Cloud Computing",
    },
    {
      _id: "jK-mnbTyReHX",
      totalSales: 1156,
      title: "Full-Stack JavaScript Development",
      thumbnail: "https://images.unsplash.com/photo-1633356122544-f134324a6cee?q=80&w=2940&auto=format&fit=crop",
      description: "Become a professional full-stack developer with JavaScript, React, and Node.js",
      price: 3499,
      isFree: false,
      level: "Advanced",
      tutorName: "Sarah Johnson",
      tutorImage: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=2787&auto=format&fit=crop",
      category: "Web Development",
    },
    {
      _id: "pL-qrsTzUiYo",
      totalSales: 987,
      title: "Data Science Bootcamp",
      thumbnail: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2940&auto=format&fit=crop",
      description: "Master data analysis, machine learning, and visualization techniques",
      price: 3999,
      isFree: false,
      level: "Intermediate",
      tutorName: "Michael Chen",
      tutorImage: "https://images.unsplash.com/photo-1531891437562-4301cf35b7e4?q=80&w=2864&auto=format&fit=crop",
      category: "Data Science",
    },
    {
      _id: "vB-wxYzAbCdE",
      totalSales: 856,
      title: "UX/UI Design Fundamentals",
      thumbnail: "https://images.unsplash.com/photo-1541462608143-67571c6738dd?q=80&w=2940&auto=format&fit=crop",
      description: "Learn user experience and interface design principles for modern applications",
      price: 2499,
      isFree: false,
      level: "Beginner",
      tutorName: "Emma Thompson",
      tutorImage: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=2522&auto=format&fit=crop",
      category: "Design",
    },
    {
      _id: "qR-stuVwXyZ1",
      totalSales: 789,
      title: "Python for Machine Learning",
      thumbnail: "https://images.unsplash.com/photo-1526379879527-8559ecfcaec0?q=80&w=2942&auto=format&fit=crop",
      description: "Apply Python to build machine learning models and solve real-world problems",
      price: 3299,
      isFree: false,
      level: "Advanced",
      tutorName: "David Lee",
      tutorImage: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=2787&auto=format&fit=crop",
      category: "Machine Learning",
    },
    {
      _id: "fG-hijKlMnOp",
      totalSales: 712,
      title: "Mobile App Development with Flutter",
      thumbnail: "https://images.unsplash.com/photo-1551650992-ee4fd47df41f?q=80&w=2787&auto=format&fit=crop",
      description: "Build cross-platform mobile apps for iOS and Android with Flutter",
      price: 2799,
      isFree: false,
      level: "Intermediate",
      tutorName: "Priya Patel",
      tutorImage: "https://images.unsplash.com/photo-1590649632960-fc903f867178?q=80&w=2787&auto=format&fit=crop",
      category: "Mobile Development",
    },
    {
      _id: "tU-vwxYzAbCd",
      totalSales: 654,
      title: "DevOps & CI/CD Pipeline Mastery",
      thumbnail: "https://images.unsplash.com/photo-1607743386760-88f10d53d237?q=80&w=2940&auto=format&fit=crop",
      description: "Learn DevOps principles and implement CI/CD pipelines for software development",
      price: 3599,
      isFree: false,
      level: "Advanced",
      tutorName: "Alex Rodriguez",
      tutorImage: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=2940&auto=format&fit=crop",
      category: "DevOps",
    },
    {
      _id: "iJ-klmNoPqRs",
      totalSales: 598,
      title: "Web Security & Ethical Hacking",
      thumbnail: "https://images.unsplash.com/photo-1614064548237-096f735f344f?q=80&w=2940&auto=format&fit=crop",
      description: "Learn to protect web applications and systems from cyber attacks",
      price: 3899,
      isFree: false,
      level: "Advanced",
      tutorName: "Marcus Wilson",
      tutorImage: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=2787&auto=format&fit=crop",
      category: "Cyber Security",
    },
    {
      _id: "eF-ghiJkLmNo",
      totalSales: 532,
      title: "Blockchain Development",
      thumbnail: "https://images.unsplash.com/photo-1639322537228-f710d846310a?q=80&w=2832&auto=format&fit=crop",
      description: "Build decentralized applications using blockchain technology",
      price: 4999,
      isFree: false,
      level: "Advanced",
      tutorName: "Sophia Wang",
      tutorImage: "https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=2788&auto=format&fit=crop",
      category: "Blockchain",
    },
    {
      _id: "aB-cdeFgHiJk",
      totalSales: 487,
      title: "React JS: Zero to Hero",
      thumbnail: "https://images.unsplash.com/photo-1633356122102-3fe601e05bd2?q=80&w=2940&auto=format&fit=crop",
      description: "Master React and build modern web applications from scratch",
      price: 2499,
      isFree: false,
      level: "Intermediate",
      tutorName: "James Wilson",
      tutorImage: "https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?q=80&w=2788&auto=format&fit=crop",
      category: "Web Development",
    },
  ]
  
  // Top Categories
  export const topCategories = [
    {
      _id: "cat-web-dev",
      title: "Web Development",
      totalSales: 8765,
      thumbnail: "https://images.unsplash.com/photo-1621839673705-6617adf9e890?q=80&w=2832&auto=format&fit=crop",
    },
    {
      _id: "cat-data-sci",
      title: "Data Science",
      totalSales: 6543,
      thumbnail: "https://images.unsplash.com/photo-1518186285589-2f7649de83e0?q=80&w=2874&auto=format&fit=crop",
    },
    {
      _id: "cat-cloud",
      title: "Cloud Computing",
      totalSales: 5432,
      thumbnail: "https://images.unsplash.com/photo-1614064641938-3bbee52942c7?q=80&w=2940&auto=format&fit=crop",
    },
    {
      _id: "cat-mobile",
      title: "Mobile Development",
      totalSales: 4981,
      thumbnail: "https://images.unsplash.com/photo-1526498460520-4c246339dccb?q=80&w=2940&auto=format&fit=crop",
    },
    {
      _id: "cat-design",
      title: "UX/UI Design",
      totalSales: 4567,
      thumbnail: "https://images.unsplash.com/photo-1561070791-2526d30994b5?q=80&w=2864&auto=format&fit=crop",
    },
    {
      _id: "cat-ml",
      title: "Machine Learning",
      totalSales: 3987,
      thumbnail: "https://images.unsplash.com/photo-1535378917042-10a22c95931a?q=80&w=2938&auto=format&fit=crop",
    },
    {
      _id: "cat-devops",
      title: "DevOps",
      totalSales: 3654,
      thumbnail: "https://images.unsplash.com/photo-1618044733300-9472054094ee?q=80&w=2940&auto=format&fit=crop",
    },
    {
      _id: "cat-security",
      title: "Cyber Security",
      totalSales: 3421,
      thumbnail: "https://images.unsplash.com/photo-1563013544-824ae1b704d3?q=80&w=2940&auto=format&fit=crop",
    },
    {
      _id: "cat-blockchain",
      title: "Blockchain",
      totalSales: 2987,
      thumbnail: "https://images.unsplash.com/photo-1621504450181-5d356f61d307?q=80&w=2940&auto=format&fit=crop",
    },
    {
      _id: "cat-game-dev",
      title: "Game Development",
      totalSales: 2765,
      thumbnail: "https://images.unsplash.com/photo-1511512578047-dfb367046420?q=80&w=2871&auto=format&fit=crop",
    },
  ]
  
  // Top Brands (in this context, likely representing course providers or instructors)
  export const topBrands = [
    {
      _id: "brand-microsoft",
      title: "Microsoft Learn",
      totalSales: 15432,
      thumbnail:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/4/44/Microsoft_logo.svg/2048px-Microsoft_logo.svg.png",
      description: "Official Microsoft courses for Azure and related technologies",
    },
    {
      _id: "brand-google",
      title: "Google Cloud",
      totalSales: 12876,
      thumbnail: "https://cloud.google.com/_static/cloud/images/social-icon-google-cloud-1200-630.png",
      description: "Official Google courses for cloud and web technologies",
    },
    {
      _id: "brand-aws",
      title: "AWS Training",
      totalSales: 11543,
      thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTC9EgQAr3Tk-n64_scQN3L8RL3qM6O4NSvYHlB&s",
      description: "Amazon Web Services official training programs",
    },
    {
      _id: "brand-cisco",
      title: "Cisco Learning",
      totalSales: 9876,
      thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuGZuWRXTabdGZ9BhR3-x_PZ86R_fsbwXW6Lqt&s",
      description: "Networking and security training from Cisco",
    },
    {
      _id: "brand-oracle",
      title: "Oracle University",
      totalSales: 8765,
      thumbnail: "https://companieslogo.com/img/orig/ORCL-d5a587ae.png?t=1633210264",
      description: "Database and enterprise software training",
    },
    {
      _id: "brand-udemy",
      title: "Udemy Business",
      totalSales: 7654,
      thumbnail: "https://s.udemycdn.com/meta/default-meta-image-v2.png",
      description: "Professional courses across all technology domains",
    },
    {
      _id: "brand-coursera",
      title: "Coursera",
      totalSales: 6543,
      thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQJ7FeUg6joRSkkAaa13bX2Qw37GFbZK-GQK3rw&s",
      description: "University-backed tech and business courses",
    },
    {
      _id: "brand-pluralsight",
      title: "Pluralsight",
      totalSales: 5432,
      thumbnail: "https://www.pluralsight.com/content/dam/pluralsight/newsroom/brand-assets/ps-logo-v-gradient.png",
      description: "Technology skill development and engineering courses",
    },
    {
      _id: "brand-linkedin",
      title: "LinkedIn Learning",
      totalSales: 4321,
      thumbnail:
        "https://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/LinkedIn_logo_initials.png/800px-LinkedIn_logo_initials.png",
      description: "Professional skills and career development",
    },
    {
      _id: "brand-datacamp",
      title: "DataCamp",
      totalSales: 3987,
      thumbnail: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTHp_FwSfcDJsGg4f_rQk6_mTYdTf5ILcBcL6Gs&s",
      description: "Data science and analytics learning platform",
    },
  ]
  